plugins {
    id 'java-library'
    id "com.vanniktech.maven.publish" version "0.28.0"
}

// Configuração da Toolchain Java (forma moderna e recomendada)
java {
    toolchain {
        // Define a versão de linguagem Java 17,11,8
        languageVersion = JavaLanguageVersion.of(8)
    }
    // Cria automaticamente a tarefa javadocJar
    // withJavadocJar()
}

def props = new Properties()
file("src/main/resources/konduto.properties").withInputStream { props.load(it) }

group = 'com.konduto.sdk'
version = props["version"]

// ext {
//     // Export java version
//     javaBuildVersion = java.toolchain.languageVersion.get().asInt()
// }

sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
        resources {
            srcDirs = ['src/main/resources']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Dependência de produção
    implementation 'com.google.code.gson:gson:2.9.0'
    // Dependências de teste
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.github.tomakehurst:wiremock-jre8:3.0.1'
}

task sourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from sourceSets.main.allSource
}

task javadocJar(type: Jar) {
    dependsOn javadoc
    archiveClassifier.set('javadoc')
    from javadoc.destinationDir
}

// Configuração do JAR principal
jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

mavenPublishing {
    coordinates(group, "java-sdk", version)

    pom {
        name = 'Konduto\'s Java SDK'
        description = 'Easily integrate with Konduto (https://konduto' +
                        '.com), a fraud prevention service.'
        inceptionYear = "2025"
        url = 'https://konduto.com'
        licenses {
            license {
                name = 'The Apache License, Version 2.0'
                url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
            }
        }
        developers {
            developer {
                id = 'danilo.carmo'
                name = 'Danilo Carmo'
                email = 'danilo.carmo@boavistascpc.com.br'
            }
        }
        scm {
            connection = 'https://github.com/konduto/java-sdk'
            developerConnection = 'https://github.com/konduto/java-sdk'
            url = 'https://github.com/konduto/java-sdk'
        }
        // properties {
	    //     // Get toolchain version
	    //     'java.build.version' = project.javaBuildVersion
	    // }

    }

    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)

    // Enable GPG (obrigatorio)
    signAllPublications()
}