# Credenciais do Novo Portal (Geradas em 'View Account' -> 'Generate Token')
mavenCentralUsername=gRpXIl
mavenCentralPassword=8zfZoMQ0yJZabDzHdV3XhjzbTuULB0MvV

# Configuração GPG (A mesma que você já usava)
signing.keyId=FB90A33A
signing.password=ATiwmN6zK#7VcHe
#decomentar para local
#signing.secretKeyRingFile=/home/local/BVS/tr_srsilva/Downloads/java-jdk-key/secring.gpg
signing.secretKeyRingFile=/root/secring.gpg
