{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "nexus",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "nexus-0.28.0.jar",
          "url": "nexus-0.28.0.jar",
          "size": 80278,
          "sha512": "eb4557cd1a66080c9c03a406808476f38b5e635d56111bc1f551184ba19602fd2d202bbd2e15f19971e11cbe2a1cd53adc0eb9371179def479f41ca020ba6cca",
          "sha256": "387f3283eeb01589c540cf26e355ba10ead097fc55c10aa483c1624950183df6",
          "sha1": "87cb2c49639428e2f4c4654121980ce7e600faf8",
          "md5": "fe987a6a37652c3134d0acd8bc4742e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "nexus-0.28.0.jar",
          "url": "nexus-0.28.0.jar",
          "size": 80278,
          "sha512": "eb4557cd1a66080c9c03a406808476f38b5e635d56111bc1f551184ba19602fd2d202bbd2e15f19971e11cbe2a1cd53adc0eb9371179def479f41ca020ba6cca",
          "sha256": "387f3283eeb01589c540cf26e355ba10ead097fc55c10aa483c1624950183df6",
          "sha1": "87cb2c49639428e2f4c4654121980ce7e600faf8",
          "md5": "fe987a6a37652c3134d0acd8bc4742e1"
        }
      ]
    }
  ]
}
