{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vanniktech",
    "module": "central-portal",
    "version": "0.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "central-portal-0.28.0.jar",
          "url": "central-portal-0.28.0.jar",
          "size": 41898,
          "sha512": "9d8d670f6aa8596556897355fa1bbe8b87b160c25eb30363c00dc4b26d0819d5e0cc400245f74c8fb63a79c948f2a39ac5a4b53e49ed576746a07d90cb8d747c",
          "sha256": "9507ca2b76de4d31e28c8a18a8f6c9bdf05e4a413bbeff7afdd1425d23c715f6",
          "sha1": "73f205c6b01b91134953ea0e9c20c3ca5af2c871",
          "md5": "e35f3ca2d50b8365a75cc298b07bb3a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.1"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-moshi",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-scalars",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "central-portal-0.28.0.jar",
          "url": "central-portal-0.28.0.jar",
          "size": 41898,
          "sha512": "9d8d670f6aa8596556897355fa1bbe8b87b160c25eb30363c00dc4b26d0819d5e0cc400245f74c8fb63a79c948f2a39ac5a4b53e49ed576746a07d90cb8d747c",
          "sha256": "9507ca2b76de4d31e28c8a18a8f6c9bdf05e4a413bbeff7afdd1425d23c715f6",
          "sha1": "73f205c6b01b91134953ea0e9c20c3ca5af2c871",
          "md5": "e35f3ca2d50b8365a75cc298b07bb3a2"
        }
      ]
    }
  ]
}
